name="ueta-frontend"
account_id = "f3e84daad81f86ff96c739f92d81f798"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-09-15"
vars = { ENV_TYPE = "dev" }

[assets]
directory = "./dist"
binding = "__STATIC_CONTENT"


[[d1_databases]]
binding = "DB"
database_name = "ueta-dev"
database_id = "6cc508bf-4c26-4142-8b0f-48d19d169659"
migrations_dir = "migrations"
preview_database_id = "DB"

[env.prod]
vars = { ENV_TYPE = "prod" }
d1_databases = [
    { binding = "DB", database_name = "ueta-prod", database_id = "your_DB_id", migrations_dir = "migrations" },
]